# SHORT URL
### Create short url
POST http://localhost:3000/url
Content-Type: application/json

{
    "slug": "example",
    "url": "http://example.com"
}

### Get long url back
GET http://localhost:3000/example